### ISSUE TITLE
Crash when start the modpack

### ISSUE THREAD

**Issue by lostopkk** [Deftu/CrashBrander#1]
![image](https://user-images.githubusercontent.com/50776714/190880872-3d251571-08ae-4aa1-bf99-5f3364966a8a.png)

**Comment by Deftu** [comment]
Hello! Mind attaching your modpack's CrashBrander config file?

**Comment by lostopkk** [comment]
![image](https://user-images.githubusercontent.com/50776714/190914119-699902d2-80c7-4717-8e55-2feead01cef7.png)
totally empty

**Comment by Deftu** [comment]
That's probably the issue. Just add two curly braces (`{}`) and it shouldn't crash anymore

**Comment by lostopkk** [comment]
solved, but it's good to do an update to fix this, thanks for the support
