### ISSUE TITLE
Version 1.4.0 requires DeftuLib 1.3.0, which is not available on CF/Modrinth

### ISSUE THREAD

**Issue by The-Fireplace** [Deftu/CrashBrander#3]
![image](https://user-images.githubusercontent.com/5914284/206821053-b6a72ac0-5a09-445b-b570-ede32f55978c.png)

**Comment by Deftu** [comment]
Oh my god how did I let that slip 😭

**Comment by Deftu** [comment]
Fixed in 57dda5b0463ba1c607c4a6924962b80a69edf286.
